FROM hexpm/elixir:1.14.2-erlang-25.1.2-debian-bullseye-20221004-slim

RUN apt-get update && \
    apt-get install -y build-essential inotify-tools && \
    mix local.hex --force && \
    mix local.rebar --force
